FROM python:3.14.2-slim 

# https://docs.astral.sh/uv/guides/integration/docker/ 
COPY --from=ghcr.io/astral-sh/uv:0.9.17 /uv /uvx /bin/

WORKDIR /workspace

ENV UV_TOOL_BIN_DIR=/usr/local/bin
ENV UV_PROJECT_ENVIRONMENT=.venv
ENV PATH="/workspace/.venv/bin:$PATH"
ENV PYTHONPATH="/workspace/src"

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      bash \
      curl \
      git \
      vim \
      dumb-init \
      ca-certificates \
      build-essential \
      libxml2-dev \
      libxslt1-dev \
      zlib1g-dev \
      bison \
      flex \
 && rm -rf /var/lib/apt/lists/*

COPY .bashrc /root/.bashrc

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
